#!/usr/bin/env python3
"""
Convert Deep Research Markdown reports to McKinsey-style HTML.
Usage: python3 md_to_html.py <report.md> [--open]
"""

import sys
import re
import os
from pathlib import Path

TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Noto+Sans+SC:wght@300;400;500;600;700&display=swap');

  :root {{
    --primary: #1a365d;
    --secondary: #2d5a8e;
    --accent: #e53e3e;
    --bg: #ffffff;
    --bg-alt: #f7f8fa;
    --text: #2d3748;
    --text-light: #718096;
    --border: #e2e8f0;
    --shadow: 0 1px 3px rgba(0,0,0,0.08);
  }}

  * {{ margin: 0; padding: 0; box-sizing: border-box; }}

  body {{
    font-family: 'Inter', 'Noto Sans SC', -apple-system, sans-serif;
    color: var(--text);
    background: var(--bg);
    line-height: 1.7;
    font-size: 15px;
    -webkit-font-smoothing: antialiased;
  }}

  .container {{
    max-width: 900px;
    margin: 0 auto;
    padding: 60px 40px;
  }}

  /* Cover */
  .cover {{
    text-align: center;
    padding: 80px 0 60px;
    border-bottom: 3px solid var(--primary);
    margin-bottom: 50px;
  }}
  .cover h1 {{
    font-size: 32px;
    font-weight: 700;
    color: var(--primary);
    letter-spacing: -0.5px;
    margin-bottom: 16px;
  }}
  .cover .meta {{
    font-size: 14px;
    color: var(--text-light);
    line-height: 1.8;
  }}

  /* Headings */
  h2 {{
    font-size: 22px;
    font-weight: 700;
    color: var(--primary);
    margin: 48px 0 20px;
    padding-bottom: 8px;
    border-bottom: 2px solid var(--primary);
  }}
  h3 {{
    font-size: 17px;
    font-weight: 600;
    color: var(--secondary);
    margin: 32px 0 12px;
  }}
  h4 {{
    font-size: 15px;
    font-weight: 600;
    color: var(--text);
    margin: 24px 0 8px;
  }}

  /* Text */
  p {{ margin: 12px 0; }}
  strong {{ font-weight: 600; }}

  /* Tables */
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
    font-size: 13.5px;
    box-shadow: var(--shadow);
  }}
  thead {{ background: var(--primary); color: white; }}
  th {{
    padding: 10px 14px;
    text-align: left;
    font-weight: 500;
    font-size: 12.5px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  td {{
    padding: 10px 14px;
    border-bottom: 1px solid var(--border);
  }}
  tbody tr:nth-child(even) {{ background: var(--bg-alt); }}
  tbody tr:hover {{ background: #edf2f7; }}

  /* Callout boxes */
  blockquote {{
    margin: 20px 0;
    padding: 16px 20px;
    background: #fff5f5;
    border-left: 4px solid var(--accent);
    font-size: 14px;
    color: #742a2a;
    border-radius: 0 6px 6px 0;
  }}
  blockquote strong {{ color: var(--accent); }}

  /* Lists */
  ul, ol {{
    margin: 12px 0;
    padding-left: 28px;
  }}
  li {{
    margin: 6px 0;
  }}
  li::marker {{ color: var(--secondary); }}

  /* Code / highlight */
  code {{
    font-family: 'SF Mono', 'Fira Code', monospace;
    font-size: 13px;
    background: var(--bg-alt);
    padding: 2px 6px;
    border-radius: 3px;
  }}

  /* Dividers */
  hr {{
    border: none;
    border-top: 1px solid var(--border);
    margin: 40px 0;
  }}

  /* Print */
  @media print {{
    body {{ font-size: 12px; }}
    .container {{ padding: 20px; max-width: 100%; }}
    .cover {{ padding: 40px 0 30px; }}
    h2 {{ page-break-before: auto; }}
    table {{ font-size: 11px; page-break-inside: avoid; }}
    blockquote {{ page-break-inside: avoid; }}
  }}

  /* Footer */
  .footer {{
    margin-top: 60px;
    padding-top: 20px;
    border-top: 1px solid var(--border);
    text-align: center;
    font-size: 12px;
    color: var(--text-light);
  }}
</style>
</head>
<body>
<div class="container">
{content}
<div class="footer">
  Generated by Deep Research Workflow &middot; Claude Opus 4.6 &middot; {date}
</div>
</div>
</body>
</html>"""


def md_to_html_content(md_text: str) -> tuple[str, str, str]:
    """Convert markdown to HTML content. Returns (title, date, html_body)."""
    lines = md_text.strip().split('\n')

    # Extract frontmatter
    title = "Research Report"
    date = ""
    in_frontmatter = False
    content_start = 0

    for i, line in enumerate(lines):
        if line.strip() == '---':
            if not in_frontmatter:
                in_frontmatter = True
                continue
            else:
                content_start = i + 1
                break
        if in_frontmatter:
            if line.startswith('title:'):
                title = line.split(':', 1)[1].strip()
            elif line.startswith('date:'):
                date = line.split(':', 1)[1].strip()

    body = '\n'.join(lines[content_start:])

    # Convert markdown to HTML
    html_parts = []
    in_table = False
    table_rows = []
    in_list = False
    list_type = None
    list_items = []

    def flush_list():
        nonlocal in_list, list_items, list_type
        if list_items:
            tag = 'ol' if list_type == 'ol' else 'ul'
            items = ''.join(f'<li>{item}</li>' for item in list_items)
            html_parts.append(f'<{tag}>{items}</{tag}>')
            list_items = []
            in_list = False

    def flush_table():
        nonlocal in_table, table_rows
        if table_rows:
            html = '<table><thead><tr>'
            headers = [c.strip() for c in table_rows[0].strip('|').split('|')]
            for h in headers:
                html += f'<th>{inline_format(h)}</th>'
            html += '</tr></thead><tbody>'
            for row in table_rows[2:]:  # skip separator
                cells = [c.strip() for c in row.strip('|').split('|')]
                html += '<tr>'
                for c in cells:
                    html += f'<td>{inline_format(c)}</td>'
                html += '</tr>'
            html += '</tbody></table>'
            html_parts.append(html)
            table_rows = []
            in_table = False

    def inline_format(text: str) -> str:
        # Bold
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
        # Italic
        text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
        # Code
        text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
        # Links
        text = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', text)
        return text

    for line in body.split('\n'):
        stripped = line.strip()

        # Table
        if stripped.startswith('|') and '|' in stripped[1:]:
            if not in_table:
                flush_list()
                in_table = True
            table_rows.append(stripped)
            continue
        elif in_table:
            flush_table()

        # Headers
        if stripped.startswith('# '):
            flush_list()
            # Main title → cover
            t = inline_format(stripped[2:])
            html_parts.append(f'<div class="cover"><h1>{t}</h1><div class="meta">{date}</div></div>')
            continue
        if stripped.startswith('## '):
            flush_list()
            html_parts.append(f'<h2>{inline_format(stripped[3:])}</h2>')
            continue
        if stripped.startswith('### '):
            flush_list()
            html_parts.append(f'<h3>{inline_format(stripped[4:])}</h3>')
            continue
        if stripped.startswith('#### '):
            flush_list()
            html_parts.append(f'<h4>{inline_format(stripped[5:])}</h4>')
            continue

        # Blockquote
        if stripped.startswith('> '):
            flush_list()
            html_parts.append(f'<blockquote>{inline_format(stripped[2:])}</blockquote>')
            continue

        # HR
        if stripped == '---' or stripped == '***':
            flush_list()
            html_parts.append('<hr>')
            continue

        # Unordered list
        if re.match(r'^[-*] ', stripped):
            if not in_list or list_type != 'ul':
                flush_list()
                in_list = True
                list_type = 'ul'
            list_items.append(inline_format(stripped[2:]))
            continue

        # Ordered list
        m = re.match(r'^(\d+)\. ', stripped)
        if m:
            if not in_list or list_type != 'ol':
                flush_list()
                in_list = True
                list_type = 'ol'
            list_items.append(inline_format(stripped[len(m.group(0)):]))
            continue

        # Empty line
        if not stripped:
            flush_list()
            continue

        # Paragraph
        flush_list()
        html_parts.append(f'<p>{inline_format(stripped)}</p>')

    flush_list()
    flush_table()

    return title, date, '\n'.join(html_parts)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 md_to_html.py <report.md> [--open]")
        sys.exit(1)

    md_path = Path(sys.argv[1])
    should_open = '--open' in sys.argv

    if not md_path.exists():
        print(f"Error: {md_path} not found")
        sys.exit(1)

    md_text = md_path.read_text(encoding='utf-8')
    title, date, content = md_to_html_content(md_text)

    html = TEMPLATE.format(title=title, content=content, date=date or 'N/A')

    out_path = md_path.with_suffix('.html')
    out_path.write_text(html, encoding='utf-8')
    print(f"✅ Generated: {out_path} ({len(html)} bytes)")

    if should_open:
        os.system(f'open "{out_path}"')


if __name__ == '__main__':
    main()
